#!/usr/bin/env python3

from sagemaker_training import entry_point, environment

env = environment.Environment()

# read hyperparameters as script arguments
args = env.to_cmd_args()

# get the environment variables
env_vars = env.to_env_vars()

# execute the entry point
entry_point.run(uri=env.module_dir,
                #user_entry_point=env.user_entry_point,
                user_entry_point='serve.R',
                args=args,
                env_vars=env_vars)
